'use client';
import {useMemo,useState} from 'react';
type Product={id:number;name:string;brand:string;cat:string;price:number;old:number;rating:number;reviews:string;emoji:string;tag:string};
const products:Product[]=[
{id:1,name:'AirFlex Pro Headphones',brand:'SoundMax',cat:'Electronics',price:3499,old:4999,rating:4.8,reviews:'2.4k',emoji:'🎧',tag:'BESTSELLER'},
{id:2,name:'Nova X Smartwatch',brand:'TechPulse',cat:'Wearables',price:4299,old:5999,rating:4.7,reviews:'1.8k',emoji:'⌚',tag:'AI PICK'},
{id:3,name:'Urban Everyday Sneakers',brand:'Stride',cat:'Fashion',price:2199,old:3299,rating:4.6,reviews:'3.1k',emoji:'👟',tag:'TRENDING'},
{id:4,name:'AeroBlend Mixer',brand:'HomeCraft',cat:'Home',price:2799,old:3999,rating:4.8,reviews:'980',emoji:'🥤',tag:'25% OFF'},
{id:5,name:'ProBook Wireless Keyboard',brand:'KeyWorks',cat:'Electronics',price:1899,old:2499,rating:4.5,reviews:'1.2k',emoji:'⌨️',tag:'VALUE'},
{id:6,name:'Luma Desk Lamp',brand:'BrightLab',cat:'Home',price:1299,old:1799,rating:4.7,reviews:'760',emoji:'💡',tag:'AI PICK'},
{id:7,name:'Everyday Travel Backpack',brand:'Nomad',cat:'Fashion',price:1599,old:2299,rating:4.6,reviews:'2k',emoji:'🎒',tag:'POPULAR'},
{id:8,name:'FitBuds Active',brand:'SoundMax',cat:'Wearables',price:2499,old:3499,rating:4.7,reviews:'1.5k',emoji:'🎵',tag:'15% OFF'}];
const cats=['All','AI Picks','Electronics','Wearables','Fashion','Home'];
export default function Home(){const[q,setQ]=useState('');const[cat,setCat]=useState('All');const[cart,setCart]=useState<number[]>([]);const[open,setOpen]=useState(false);const[compare,setCompare]=useState<number[]>([]);const[toast,setToast]=useState('');
const list=useMemo(()=>products.filter(p=>(cat==='All'||(cat==='AI Picks'?p.tag==='AI PICK':p.cat===cat))&&(p.name+' '+p.brand+' '+p.cat).toLowerCase().includes(q.toLowerCase())),[q,cat]);const total=cart.reduce((s,id)=>s+(products.find(p=>p.id===id)?.price||0),0);const notify=(s:string)=>{setToast(s);setTimeout(()=>setToast(''),1500)};const add=(id:number)=>{setCart(c=>[...c,id]);notify('Added to cart')};
return <main><header><div className="logo">S</div><div className="brand">ShopSmart <span>AI Pro</span></div><nav><button onClick={()=>setCat('All')}>Discover</button><button onClick={()=>{setCat('AI Picks');notify('Showing AI-selected products')}}>AI Picks ✦</button><button onClick={()=>notify('Price comparison is active on every product')}>Compare</button></nav><button className="cart" onClick={()=>setOpen(true)}>🛒 <b>{cart.length}</b></button></header>
<section className="hero"><div><span className="eyebrow">✦ SHOPPING, UPGRADED</span><h1>Buy better.<br/><em>Spend smarter.</em></h1><p>Shop thousands of products with AI-powered recommendations, transparent comparisons and smarter choices.</p><div className="search"><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search products, brands, categories..."/><button onClick={()=>document.getElementById('products')?.scrollIntoView({behavior:'smooth'})}>Search</button></div><div className="proof"><b>50K+ <small>products</small></b><b>4.8★ <small>shopper rating</small></b><b>98% <small>recommendation accuracy</small></b></div></div><div className="heroArt"><div className="orb">🛍️</div><div className="float f1">✦ <b>92% match</b><small>AI recommendation</small></div><div className="float f2">↓ <b>Best price</b><small>Found for you</small></div></div></section>
<section className="ai"><div className="spark">✦</div><div><b>Let AI do the shopping</b><p>Tell us what you need. We'll shortlist the best options based on value, ratings and your budget.</p></div><button onClick={()=>{setCat('AI Picks');document.getElementById('products')?.scrollIntoView({behavior:'smooth'});notify('AI shortlist generated')}}>Build my shortlist →</button></section>
<section id="products" className="content"><div className="top"><div><span className="eyebrow">CURATED FOR YOU</span><h2>Smart picks, less scrolling.</h2><p>Products worth your money, selected for quality and value.</p></div><div className="cats">{cats.map(c=><button key={c} className={cat===c?'active':''} onClick={()=>setCat(c)}>{c}</button>)}</div></div><div className="grid">{list.map(p=><article className="product" key={p.id}><div className="pic"><span>{p.emoji}</span><label>{p.tag}</label><button className={compare.includes(p.id)?'chosen':''} onClick={()=>setCompare(c=>c.includes(p.id)?c.filter(x=>x!==p.id):c.length<3?[...c,p.id]:c)}>↔</button></div><div className="info"><div className="rating">★ {p.rating} <small>({p.reviews})</small></div><span className="brandname">{p.brand}</span><h3>{p.name}</h3><div className="price"><b>₹{p.price.toLocaleString('en-IN')}</b><del>₹{p.old.toLocaleString('en-IN')}</del><span>{Math.round((1-p.price/p.old)*100)}% off</span></div><button className="add" onClick={()=>add(p.id)}>Add to cart</button></div></article>)}</div>{!list.length&&<div className="empty">No products found. Try another search.</div>}</section>
{compare.length>0&&<div className="compareBar"><b>Compare {compare.length}/3</b>{compare.map(id=><span key={id}>{products.find(p=>p.id===id)?.emoji} {products.find(p=>p.id===id)?.name}</span>)}<button onClick={()=>{setCompare([]);notify('Comparison cleared')}}>Clear</button></div>}
<footer><div className="brand"><span className="mini">S</span> ShopSmart <span>AI Pro</span></div><p>Smarter choices. Better value.</p><small>© 2026 ShopSmart AI Pro</small></footer>
{toast&&<div className="toast">✓ {toast}</div>}{open&&<div className="overlay" onClick={()=>setOpen(false)}><aside onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setOpen(false)}>×</button><h2>Your cart</h2>{!cart.length?<div className="empty">Nothing here yet.<br/>Add a smart pick to get started.</div>:<>{cart.map((id,i)=>{const p=products.find(x=>x.id===id)!;return <div className="row" key={i}><span>{p.emoji}</span><div><b>{p.name}</b><small>₹{p.price.toLocaleString('en-IN')}</small></div><button onClick={()=>setCart(c=>c.filter((_,j)=>j!==i))}>×</button></div>})}<div className="total"><span>Total</span><b>₹{total.toLocaleString('en-IN')}</b></div><button className="checkout" onClick={()=>{setCart([]);setOpen(false);notify('Order placed successfully')}}>Checkout →</button></>}</aside></div>}</main>}
